### ISSUE TITLE
Review fields naming for registration page

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#27]
When registering the software requires the "name" of the user but I think it would be more appropriate to ask for a "username" which would make more sense and would be easier to understand.

**Comment by SamMousa** [comment]
No, a username is used to log in. The name in this case is for display purposes only. It is not unique for example.

**Comment by matof-who** [comment]
Hi @SamMousa 

I see why users may be confused, as "Name" is very generic and it's nowhere indicated that theire username will be their e-mail address

Do yo think this will give more clarity ?


![Image](https://user-images.githubusercontent.com/70581697/202469701-b437ec31-1747-4728-98a8-172ea0e195b1.png)


@breakhard, does this improvement need to be implemented quickly, or can it wait after the survey Js migration ?

**Comment by SamMousa** [comment]
Why would users be confused? We never ask them for a username; the concept does not exist in the platform.
![image](https://user-images.githubusercontent.com/547021/202484612-a5955f67-9c22-4a0d-ad25-37b98e7d8756.png)


Next change request they'll ask us to remove the password fields and change the email field to a dropdown so they can just pick one....
No where in this ticket there is a problem stated btw; I'm not sure at which point users supposedly get confused:
- Do they not know how to fill in their name when prompted?
- Do they not know the terms "email" and "password"?

**Comment by breakhard** [comment]
Hi both, the original issue is: when you invite people to register, it sends an email with a link to activate your account. clicking on the link opens the user profile page. There, they need to register their name: 1 - First they never really know what to put there (indeed it can sound obvious if there is "name" , they should write their name. but they wonder if it is first name + name or just name  or just first name or... username. 2 - after they need to insert a password. and... believe me or not but for some of them this is also sometimes difficult: which password? but this step is also quickly solved. But 3- when they just registered  it opens again the login popup and there they need to insert: their email + their pwd.... Psychologically , by default you just write again what you just entered previously: so NAME + PWD . I know it is clearly written "email" in the box but I guess this is not what you expect, so you dont really read it... My point of using username instead of name: 1 - At least, you don't wonder what should I put as "name" 2 - "username" contains 3 more characters than "email" , and in the end is less confusing than NAME .... It seems totally crazy but this can lead to 20 minutes before creating an account! Definitely, this is not a first priority but if not a lot to do, I guess this can help!

**Comment by SamMousa** [comment]
@breakhard please have a look at the markup, use the edit button (three dots > edit) and format your text a little. 

This is just unreadable.

**Comment by SamMousa** [comment]
This can be tested on https://herams-staging.org


![Image](https://user-images.githubusercontent.com/547021/203313623-5fd8770a-ba8b-495a-acf2-bff6ffda742f.png)

**Comment by SamMousa** [comment]
This is the platform default ui for display and not editing. I'm thinking that a readonly box will get you bug reports of users that do not understand why they cannot change the email...

**Comment by matof-who** [comment]
@SamMousa . As discussed during the weekly, please deploy your proposal on https://herams-staging.org/  to Production
