### ISSUE TITLE
Add a default language for projects

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#64]
**Current situation**

- Admin can define the available languages for a project
- Admin can define the workspaces and HF names in multiple languages

**Future situation**

- Admin can define the default language for a project
- When creating/updating a workspace or health facility
   - The name in the project default language is mandatory
- When displaying the list of workspaces/HF: 
   - System will display the  the workspace/HF name in the user's selected language
   - If that is blank, system will display the workspace/HF name in the project default language
 - When importing data
   - The name in the default project language is always mandatory (for both workspaces and HF)

**Comment by SamMousa** [comment]
How do we deal with changing the default language?
It might invalidate existing data (missing name in project primary language).

We could try to circumvent this challenge by requiring that the name is mandatory in at least 1 language. 
This however then pushes the problem to updates of additional languages.

Imagine the situation where a project has primary language English, and secondary French and Arabic.

We have **Workspace A** with only an English title available.
If we change the project default language to French validation for that workspace fails.
We loosen the constraint and require any language to be configured.
Now changing the default language doesn't cause validation failure.

Next step, the project admin removes English from the project. While we won't update the workspace data initially, when a user goes to the update screen they will see just the French name field, which is empty.



The issue here is that we have validation dependent on mutable configuration of a parent entity. Since a project may have 100s of workspaces and 1000s of facilities, revalidating them all when updating a project is not really feasible.

A solution could be to limit the changes allowed for a project; for example by allowing adding additional languages, but not removing them.

Need to have a discussion on this to decide how to move forward.

**Comment by SamMousa** [comment]
Conclusion:
- Default project language may be changed.
- Workspaces & HF & HF admin data title have the following constraint: at least 1 of the project active languages needs to have a value --> import DOES check this constraint
- Removing an additional language from a project requires platform to validate all workspaces & HF & data in the project to confirm another title value is present. this is a READONLY check. if the check does not pass, the operation is not allowed.
- survey validation will check that default project language is a required title field **optional**   import validation does not check this

**Comment by SamMousa** [comment]
Move parts to backlog

**Comment by matof-who** [comment]
Clarification required about expected behaviour. Proposal here: https://extranet.who.int/confluence/x/WoATBQ

**Comment by matof-who** [comment]
Obsolete, new platform localization tickets opened to implement new rules
